version: "3.9"
services:
  ml_service:
    build: ../ml_service
    ports:
      - "8000:8000"
    environment:
      - MODEL_PATH=/app/models/xgboost_model.pkl
    restart: unless-stopped

  api:
    build: ../api
    ports:
      - "5000:5000"
    environment:
      - ML_SERVICE_URL=http://ml_service:8000
    depends_on:
      - ml_service
    restart: unless-stopped

  frontend:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ../frontend:/app
    command: sh -c "npm ci && npm run dev -- --host"
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=/api
    depends_on:
      - api
    restart: unless-stopped

networks:
  default:
    name: mlwebapp-net
